<strong>Call for papers</strong><br>

<a href="doc/cfp.pdf">PDF version</a>

<p>
The <i> International Workshop on Similarity Search and Applications (SISAP)</i>
is a new conference devoted to similarity searching, with emphasis on metric 
space searching. It aims to fill in the gap left by the various scientific 
venues devoted to similarity searching in spaces with coordinates, by providing
a common forum for theoreticians and practitioners around the problem of 
similarity searching in general spaces (metric and non-metric) or using 
distance-based (as opposed to coordinate-based) techniques in general.
</p>

<p>
SISAP aims to become an ideal forum to exchange real-world, challenging and 
exciting 
examples of applications, new indexing techniques, common testbeds and 
benchmarks, source code, and up-to-date literature through a Web page
serving the similarity searching community. Authors are expected to use the 
testbeds and code from the SISAP Web
site for comparing new applications, databases, indexes and algorithms.
</p>



<p>
<strong>Contributions to the conference should fall into the following categories: </strong>
</p>

<p><strong>
[Basic techniques:]</strong> general methods that apply to arbitrary metric spaces,
nonmetric or (dis)similarity spaces, or high-dimensional vector spaces. We
strongly encourage that those be accompanied with an open-source implementation 
conforming the interface of the Web site and to be tested with a relevant 
subset of the spaces included in the Web site. This will favor uniform 
comparison and also permit comparing the technique with future developments. 
Yet, especially in this first edition, we can waive this requirement for good
enough submissions.
</p>
<p>
<strong>
[Applied techniques:]</strong> methods that apply to specific similarity search 
problems. Those papers are also encouraged to contribute with the code and,
especially, with the similarity computation function and the datasets related
to the specific problem they address (if they are new), for the Web site.
</p> 
<p><strong>
[Spaces and similarities:]</strong> poster papers that present challenges, in the 
form of searching in new spaces. This type of contribution is expected to
provide a thorough study of the metric space (e.g. its intrinsic dimension)
or the similarity measure, and must include code for the similarity computation
and datasets for the Web site.</p>

<strong> The topics of interest include, but are not limited to:</strong>

<ul>
<li> Range search
<li> knn search
<li> Limited-range knn search
<li> Reverse knn search
<li> Similarity joins
<li> Clustering (applied to indexing)
<li> Parallelism
<li> Approximate searching
<li> Computation of intrinsic dimension
<li> Cost models
<li> Embeddings
<li> Languages for similarity databases
</ul>

<strong>Submission instructions</strong>

<p>
Please submit an extended abstract of at most 10 pages using 11-point size and
reasonable margins (e.g. fullpage option in Latex). Those 10 pages include
title, abstract, paper body, and references. Additional appendixes
can use more pages but they will be read at the discretion of the reviewer,
so they should not be used for material that is essential to understand the
relevance of the contribution.
</p>
<p>
We remark that reviewing is <b>double-blind</b>, so please do not include author
information nor any data that discloses authorship in an obvious way.
</p>

<strong>Venue</strong>
<p>
SISAP 2008 will operate as a workshop co-located with ICDE 2008, in April 11-12, 2008.
ICDE 2008 will be held in Cancun, Mexico, see <a href="http://www.icde2008.org"> http://www.icde2008.org</a> for details.
</p>

<strong>Conference Proceedings and Special Issue</strong>

<p>
The proceedings of SISAP 2008 will be published by IEEE Computer Society Press.
</p>

<p>
A special issue with the extended versions of the best SISAP 2008 papers will appear in
the Journal of Discrete Algorithms (Elsevier).
</p>

