<p class="tituloPrincipal">1st International Workshop <br /> on Similarity Search and Applications (SISAP)
    <br />
        <span class="tituloSecundario">April 11-12
	, 2008, Canc&uacute;n, M&eacute;xico <br />
        </span></p>
    <p class="principal">
<ul>
<li><strong>Abstract submissions:]</strong> November 26, 2007.
<li><strong>[Paper submissions:]</strong> December 1, 2007.
<li><strong>[Notifications:]</strong> December 27, 2007.
<li><strong>[Camera-ready:]</strong> January 15, 2008.
<li><strong>[Workshop:]</strong> April 11-12, 2008.
</ul>
</b>
