<p class="tituloPrincipal">Metric Spaces Library
    <br />
        <span class="tituloSecundario">An open-source C-based library for metric space indexing <br />
        </span></p>
    <p class="principal">

This library contains source code implementing several indexing algorithms, as
well as metric spaces, conforming to an API that permits adding new indexes and
spaces. In addition, there are example instances and automatic generators for 
different metric spaces.
<p>
Download the source codes and manual from 
<a href="../library/metricSpaces.tar.gz">here</a> (gzipped tar).
This is the main structure of the library.
<p>
Download <i>all</i> the database instances provided from
<a href="../library/dbs.tar.gz">here</a> (gzipped tar).
Beware of its size! This will expand into a directory dbs/ that should go
inside directory metricSpaces/ of the main structure (where the directory
already exists).
<p>
If you only want some databases, then
<a href="http://www.sisap.org/library/dbs/">browse</a> them and download those you really
want. Expand them in the correct subdirectory of metricSpaces/dbs/.
<p>
The manual is inside the main structure, but you can also download it
<a href="../library/manual.pdf">directly</a>.
<p>
Send any question, problem, bug report, and new contribution (which will be
especially welcome!) to <a href="mailto:karina.figueroa@gmail.com">Karina
Figueroa</a>.
<p>
<img src="imagenes/new.png">
<b> contributions </b>
<li> From the paper <a href="library/new/countingDistPerm.tar.gz">
<i>Counting Distance Permutations</i></a> by Matthew Skala
<li> <a href="library/new/Fastss.tar.gz">FastSS algorithm (for strings)</a> by Thomas 
Bocek<br>
<uL>Include: <br> 
All files in the directory /src/indexes/fastss, and a file 
src/obj-fastss.h (needed to access the files in the db).
</ul>
<li> <a href="library/new/VSSLTest.zip">Visual similarity in sign language</a>
by Jan Ulrych.
<ul>
</ul>
<p>
