<p class="tituloPrincipal">1st International Workshop <br /> on Similarity Search and Applications (SISAP)
    <br />
        <span class="tituloSecundario">April 11-12, 2008, Canc&uacute;n, Mexico <br />
        </span></p>
    <p class="principal">
The <i>International Workshop on Similarity Search and Applications (SISAP)</i>
is a new conference devoted to similarity searching, with emphasis on metric 
space searching. It aims to fill in the gap left by the various scientific 
venues devoted to similarity searching in spaces with coordinates, by providing
a common forum for theoreticians and practitioners around the problem of 
similarity searching in general spaces (metric and non-metric) or using 
distance-based (as opposed to coordinate-based) techniques in general.    </p>
    
    <p class="principal">

SISAP aims to become an ideal forum to exchange real-world, challenging and 
exciting examples of applications, new indexing techniques, common testbeds and 
benchmarks, source code, and up-to-date literature through a Web page serving 
the similarity searching community. Authors are expected to use the testbeds 
and code from the SISAP Web site for comparing new applications, databases, 
indexes and algorithms.
    </p> 