<p class="tituloPrincipal">Organization<br />
</p>
<p> <span class="tituloSecundario">Technical Program Co-Chairs </span> <br> 
    <span class=principal>
	<a href="mailto:elchavez@fismat.umich.mx">Edgar Chavez</a> <br> 
	<a href="mailto:gnavarro@dcc.uchile.cl">Gonzalo Navarro</a></span>
</p>

<p> <span class="tituloSecundario">Publicity Chair</span> <br> 
    <span class=principal>
	<a href="mailto:mpatella@deis.unibo.it">Marco Patella</a></span>
</p>

<p> <span class="tituloSecundario">Local Organization</span> <br> 
    <span class=principal> Co-located with 
     <a href="http://www.icde2008.org">ICDE 2008</a>
     </span>
</p>

