<p class="tituloPrincipal">Technical Program Committee<br />
</p>
<table>
<tr>
<td width=50%>
<p><span class="name">   Edgar Ch&aacute;vez <b>co-chair</b></span><br><span class="tiny">Universidad Michoacana, M&eacute;xico
<p><span class="name"> Paolo Ciaccia</span><br><span class="tiny">Universit&aacute; di Bologna, Italy</span></p>
<p><span class="name"> Alfredo Ferro</span><br><span class="tiny">Universit&aacute; di Catania, Italy</span></p>
<p><span class="name"> Daniel Keim</span><br><span class="tiny"> Universitat Konstanz, Germany</span></p>
<p><span class="name"> Daniel Miranker</span><br><span class="tiny">University of Texas at Austin, USA</span></p>
<p><span class="name"> Gonzalo Navarro <b> co-chair</b></span><br><span class="tiny"> Universidad de Chile,
Chile</span></p>
<p><span class="name"> Marco Patella</span><br><span class="tiny"> Universit&aacute; di Bologna, Italy</span></p>
<p><span class="name"> Hanan Samet</span><br><span class="tiny">University of Maryland, USA</span></p>
<p><span class="name"> Tom&aacute;s Skopal</span><br><span class="tiny">Charles University in Prague, Czech
Republic</span></p>
<p><span class="name"> Pavel Zezula</span><br><span class="tiny">Masaryk University, Czech Republic</span></p>


</span></p>
</td>
</table>



