<h1>Conference Program</h1>
        </span></p>
    <p class="name">

<p class="p2"><b class="name">Friday 11th</b>

<p class="p3"><b class="name">13:30-13:40</b> Welcome</p>

<p class="p2"><b class="name">13:40-14:30 </b> Invited Talk</p>
<ul>
<li class="name"><a href="talks/Evolving-Models-of-Biological-Sequence-Similarity.ppt">Evolving Models of Biological Sequence Similarity</a>
  <br><i>Daniel Miranker</i><p>
</ul>
<p class="p3"><b>14:30-14:45</b> break</p>

<p class="p3"><b>14:45-16:00</b> Session 1: Searching in Specific Metric Spaces</p>
<ul>
	<li class="name">HiPeR : Hierarchical Progressive Exact Retrieval in Multi-dimensional Spaces
	  <br><i>Nouha Bouteldja, Valerie Gouet-Brunet and Michel Scholl</i><p>
	  <li class="name">High-Dimensional Similarity Retrieval Using Dimensional Choice
	    <br><i>Dave Tahmoush and Hanan Samet</i><p>
	    <li class="name"><a href="talks/Approximate-Similarity-Search-in-Sequence-Databases-using-Landmark-Guided-Embedding.ppt">Approximate Similarity Search in Sequence Databases using Landmark-Guided Embedding</a>
  	    <br><i>Ahmet Sacan and Ismail Toroslu</i><p>
</ul>
<p class="p3"><b>16:00-16:15</b> break</p>
<p class="p3"><b>16:15-17:30</b> Session 2: Spaces and Similarities</p>
<ul>
	<li class="name"><a href="talks/Visual-Similarity-In-Sign-Language.pdf">Visual Similarity in Sign Language</a>
	  <br><i>Jan Ulrych and Michal Kopecky</i><p>
	  <li class="name"><a href="talks/A-Contextual-Normalised-Edit-Distance.pdf">A Contextual Normalised Edit Distance</a>
  	  <br><i>Colin de la Higuera and Luisa Mico</i><p>
	  <li class="name"><a href="talks/Counting-Distance-Permutations.pdf">Counting Distance Permutations</a>
  	  <br><i>Matthew Skala</i><p>
</ul>
<p class="p2"><br></p>
<p class="p1"><b>Saturday 12th</b></p>
<p class="p2"><br></p>
<p class="p1"><b>9:40-10:30 </b>Invited Talk</p>

<ul>
	<li class="name"><a href="talks/The-Many-Facets-of-Approximate-Similarity-Search.ppt">The Many Facets of Approximate Similarity Search</a>
 	 <br><i>Marco Patella</i><p>
</ul>
<p class="p3"><b>10:30-10:45</b> break</p>
<p class="p3"><b>10:45-12:00 </b>Session 3: Distributed Indexes</p>
<ul>
	<li class="name">Combining Metric Features in Large Collections
  	<br><i>Michal Batko, Petra Kohoutkova and Pavel Zezula</i><p>
	<li class="name">Similarity Searching: Towards Bulk-loading Peer-to-Peer Networks
  	<br><i>Vlastislav Dohnal, Jan Sedmidubsky, Pavel Zezula and David Novak</i><p>
	<li class="name"><a href="talks/An-Empirical-Evaluation-of-a-Distributed-Clustering-based-Index-for-Metric-Space-Databases.pdf">An Empirical Evaluation of a Distributed Clustering-based Index for Metric Space Databases</a>
  	<br><i>Veronica Gil-Costa, Mauricio Marin and Nora Reyes</i><p>
</ul>
<p class="p3"><b>12:00-13:30</b> lunch</p>
<p class="p3"><b>13:30-14:45</b> Session 4: Index (Re)Organization</p>
<ul>
	<li class="name"><a href="talks/A-Dynamic-Pivot-Selection-Technique-for-Similarity-Search.pdf">A Dynamic Pivot Selection Technique for Similarity Search</a>
 	 <br><i>Benjamin Bustos, Oscar Pedreira and Nieves R. Brisaboa</i><p>
	 <li class="name">Effective Use of Space for Pivot-Based Metric Indexing Structures
  	 <br><i>Cengiz Celik</i><p>
	 <li class="name"><a href="talks/On-Reinsertions-in-M-tree.ppt">On Reinsertions in M-tree</a>
  	 <br><i>Jakub Loko. and Tomas Skopal</i><p>
</ul>
<p class="p3"><b>14:45-15:00</b> break</p>
<p class="p3"><b>15:00-16:15</b> Session 5: Advanced Similarity Problems</p>
<ul>
	<li class="name"><a href="talks/List-of-twin-clusters.pdf"> List of Twin Clusters: a Data Structure for Similarity Joins in Metric Spaces</a>
  	<br><i>Rodrigo Paredes and Nora Reyes</i><p>
	<li class="name">Anytime K-Nearest Neighbor Search for Database Applications
  	<br><i>Weijia Xu, Daniel Miranker and Rui Mao</i><p>
	<li class="name"><a href="talks/On-the-Complexity-of-Reverse-Similarity-Search.pdf">On the Complexity of Reverse Similarity Search</a>
  	<br><i>Matthew Skala</i><p>
</ul>
<p class="p3"><b>16:15-16:30</b> break</p>
<p class="p3"><b>16:30-17:30</b> Panel discussion and farewell</p>
