<br>
<br>
<table align=center width=80% > 
<tr><td>We will generate a pdf document with your data. Please print and fax the registration form
to the fax number <b>printed in the form</b>. Hotel booking and AdHocNow registration (e.g. name tags) will be done with the same data.
<tr><td class=titulo> Hotel booking deadline: September 24 2005
</table>
<hline>
<form valing=top name="ccard_register" action="?x=ini_registro" method="post">
<center>
<TABLE border=0 width=80% align=center valign=top>
<td>
<table width=100% class="normal" border=0 cellpadding=0 cellspacing=0>
<tr>
	<td>&nbsp;</td>
<tr>
	<td><b>We will use your e-mail address as your record ID</b></td><td>&nbsp;</td>
<tr>
	<td>To register enter your e-mail address
<tr>
	<td>e-mail</td>
	<td><input type="text" name="email" value="Email address"></td>
	<td></td>
<tr>
	<td><input type="reset" value="Clear"></td><td><input type="submit" value="Submit"></td>
<tr>
	<td>&nbsp;</td>
</table>
<tr class="normal">
	<td>
	<p>
	<b></b><br>
	If you have already registered the registration form will be available for
	download. Otherwise you will be asked some data.
	<br>
	</p>
	</td>
</td>
</TABLE>
</center>
