<p class="tituloPrincipal">Registering for SISAP<br />
</p>
<p> <span class="tituloSecundario">This workshop is a satellite workshop of <a href="http://www.icde2008.org">ICDE 2008</a>
</span> <br> 
    <span class=principal> 
    
    For SISAP, you need at least to register in the category "Affiliated Workshops
    Only", although you might want instead to take the combo with ICDE,
    "Conference and Workshops". The student categories have only the combo
    option. Although it is slightly more expensive than a regular registration for
    "Affiliated Workshops Only", students might well be interested in attending
    ICDE for basically the same price.
    
    <br>
    
    Please register
                      <a href="http://www.icde2008.org/index.php?option=com_content&task=view&id=56&Itemid=92">here</a>

</p>

