      <table width="490" border="0" cellspacing="0" cellpadding="1" align="center">
        <tr class="todo"> 
          <td width="500"><!-- #BeginEditable "Contenido%20principal" --> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor=003366>
              <tr> 
                <td class="TituloImportante" align=center>Conference venue</td>
              </tr>
      <tr>
      <td> The workshop is co-located with <a href="http://www.icde2008.org">ICDE 2008</a>
      sharing the accommodation facilities.

      <image src="imagenes/presidente.jpg">
      <br>
      Aerial view of the Cancun Presidente Intercontinental Hotel. <br><br>Please visit ICDE 2008 site for
      hotel reservation information.

</span> </p>
      </table>
